### ISSUE TITLE
About meta-evaluation dataset with human annotations

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [THUDM/AlignBench#2]
Hello, your work are very interesting and inspired.

After reading your paper, I am very interesting with your collected meta-evaluation dataset.
But I cannot find this part of data in this repo. So, is there any plan to release this meta-evaluation in your road map?

**Comment by leixy20** [comment]
Thanks for your attention to AlignBench!
We plan to release the human-annotated dataset in near future! The dataset currently still requires some checks and validation, as we want to make sure that no harmful content or private user information is exposed in question, LLM generations and LLM judgments. Since the dataset is a bit large(8 models * 400 questions), we need some time for the manual checking. Thank you!
